#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <HalIR/halir.h>
#include <HalIR/spc.h>

static int
spc_write_header(FILE *fp, const SPCHDR *header)
{
  return fwrite(header, sizeof(SPCHDR), 1, fp) == 1;
}

static int
spc_write_subheader(FILE *fp, const SUBHDR *subheader)
{
  return fwrite(subheader, sizeof(SUBHDR), 1, fp) == 1;
}

static int
spc_write_float_array(FILE *fp, const halir_num *values, size_t count)
{
  float *buffer;

  if (count == 0) {
    return 1;
  }

  buffer = (float*)malloc(count * sizeof(float));
  if (buffer == NULL) {
    return 0;
  }

  for (size_t i = 0; i < count; i++) {
    buffer[i] = (float)values[i];
  }

  if (fwrite(buffer, sizeof(float), count, fp) != count) {
    free(buffer);
    return 0;
  }

  free(buffer);
  return 1;
}

static void
spc_fill_header(SPCHDR *header, DWORD npts, DWORD nsub, BYTE flags, BYTE ytype)
{
  memset(header, 0, sizeof(*header));
  header->ftflgs = flags;
  header->fversn = 0x4B;
  header->fexper = SPCFTIR;
  header->fexp = (char)0x80;
  header->fnpts = npts;
  header->fnsub = nsub;
  header->fxtype = XWAVEN;
  header->fytype = ytype;
  header->fztype = XARB;
  header->fwtype = XARB;
  memcpy(header->fsource, "HalIR", 6);
  memcpy(header->fcmnt, "Generated by HalIR", 19);
}

static void
spc_fill_single_subheader(SUBHDR *subheader)
{
  memset(subheader, 0, sizeof(*subheader));
  subheader->subexp = (char)0x80;
}

static BYTE
spc_result_ytype(const halir_result *result)
{
  if ((result != NULL) && (result->workspace != NULL)) {
    if (result->workspace->ftype == HALIR_TRANSMISSION) {
      return YTRANS;
    }
    if (result->workspace->ftype == HALIR_ABSORBANCE) {
      return YABSRB;
    }
  }
  return YARB;
}

int
halir_spectra_write_spc(const halir_spectra *spectra, const char *file_path)
{
  FILE *fp;
  SPCHDR header;
  SUBHDR subheader;

  if ((spectra == NULL) || (file_path == NULL) ||
      (spectra->ndatapnts == 0) || (spectra->wavenum == NULL) || (spectra->data == NULL)) {
    return 1;
  }

  fp = fopen(file_path, "wb");
  if (fp == NULL) {
    return 2;
  }

  spc_fill_header(&header, (DWORD)spectra->ndatapnts, 1, TXVALS, YARB);
  header.ffirst = spectra->wavenum[0];
  header.flast = spectra->wavenum[spectra->ndatapnts - 1];
  spc_fill_single_subheader(&subheader);

  if (!spc_write_header(fp, &header) ||
      !spc_write_float_array(fp, spectra->wavenum, spectra->ndatapnts) ||
      !spc_write_subheader(fp, &subheader) ||
      !spc_write_float_array(fp, spectra->data, spectra->ndatapnts)) {
    fclose(fp);
    return 2;
  }

  fclose(fp);
  return 0;
}

int
halir_result_write_spc(const halir_result *result, const char *file_path)
{
  FILE *fp;
  SPCHDR header;

  if ((result == NULL) || (file_path == NULL) ||
      (result->nspectra == 0) || (result->spectra == NULL)) {
    return 1;
  }

  fp = fopen(file_path, "wb");
  if (fp == NULL) {
    return 2;
  }

  spc_fill_header(&header, 0, (DWORD)result->nspectra, (BYTE)(TMULTI | TXVALS | TXYXYS), spc_result_ytype(result));
  if (result->spectra[0].ndatapnts > 0) {
    header.ffirst = result->spectra[0].wavenum[0];
    header.flast = result->spectra[0].wavenum[result->spectra[0].ndatapnts - 1];
  }
  header.fzinc = 1.0f;

  if (!spc_write_header(fp, &header)) {
    fclose(fp);
    return 2;
  }

  for (size_t i = 0; i < result->nspectra; i++) {
    SUBHDR subheader;
    const halir_spectra *spectra = &result->spectra[i];

    if ((spectra->ndatapnts == 0) || (spectra->wavenum == NULL) || (spectra->data == NULL)) {
      fclose(fp);
      return 1;
    }

    memset(&subheader, 0, sizeof(subheader));
    subheader.subexp = (char)0x80;
    subheader.subindx = (WORD)i;
    subheader.subtime = (float)i;
    subheader.subnext = (float)(i + 1);
    subheader.subnpts = (DWORD)spectra->ndatapnts;

    if (!spc_write_subheader(fp, &subheader) ||
        !spc_write_float_array(fp, spectra->wavenum, spectra->ndatapnts) ||
        !spc_write_float_array(fp, spectra->data, spectra->ndatapnts)) {
      fclose(fp);
      return 2;
    }
  }

  fclose(fp);
  return 0;
}

static int
spc_read_float_buffer(FILE *fp, size_t count, halir_num *dst)
{
  float *buffer;

  if (count == 0) {
    return 1;
  }

  buffer = (float*)malloc(count * sizeof(float));
  if (buffer == NULL) {
    return 0;
  }

  if (fread(buffer, sizeof(float), count, fp) != count) {
    free(buffer);
    return 0;
  }

  for (size_t i = 0; i < count; i++) {
    dst[i] = (halir_num)buffer[i];
  }

  free(buffer);
  return 1;
}

static int
spc_read_fixed32_buffer(FILE *fp, size_t count, signed char exponent, halir_num *dst)
{
  int32_t *buffer;

  buffer = (int32_t*)malloc(count * sizeof(int32_t));
  if (buffer == NULL) {
    return 0;
  }

  if (fread(buffer, sizeof(int32_t), count, fp) != count) {
    free(buffer);
    return 0;
  }

  for (size_t i = 0; i < count; i++) {
    dst[i] = ldexp((double)buffer[i], exponent - 32);
  }

  free(buffer);
  return 1;
}

static int
spc_read_fixed16_buffer(FILE *fp, size_t count, signed char exponent, halir_num *dst)
{
  int16_t *buffer;

  buffer = (int16_t*)malloc(count * sizeof(int16_t));
  if (buffer == NULL) {
    return 0;
  }

  if (fread(buffer, sizeof(int16_t), count, fp) != count) {
    free(buffer);
    return 0;
  }

  for (size_t i = 0; i < count; i++) {
    dst[i] = ldexp((double)buffer[i], exponent - 16);
  }

  free(buffer);
  return 1;
}

static int
spc_read_y_values(FILE *fp, size_t count, BYTE flags, signed char exponent, halir_num *dst)
{
  if (exponent == (signed char)0x80) {
    return spc_read_float_buffer(fp, count, dst);
  }
  if ((flags & TSPREC) != 0) {
    return spc_read_fixed16_buffer(fp, count, exponent, dst);
  }
  return spc_read_fixed32_buffer(fp, count, exponent, dst);
}

static void
spc_fill_linear_x(halir_spectra *spectra, double first, double last)
{
  if (spectra->ndatapnts == 1) {
    spectra->wavenum[0] = (halir_num)first;
    return;
  }

  for (size_t i = 0; i < spectra->ndatapnts; i++) {
    double frac = (double)i / (double)(spectra->ndatapnts - 1);
    spectra->wavenum[i] = (halir_num)(first + frac * (last - first));
  }
}

static halir_result *
spc_alloc_result(size_t nspectra)
{
  halir_result *result;

  result = (halir_result*)calloc(1, sizeof(halir_result));
  if (result == NULL) {
    return NULL;
  }

  result->spectra = (halir_spectra*)calloc(nspectra, sizeof(halir_spectra));
  if (result->spectra == NULL) {
    free(result);
    return NULL;
  }

  result->nspectra = nspectra;
  result->workspace = NULL;
  return result;
}

static int
spc_read_subfile_at(FILE *fp, long subfile_offset, const SPCHDR *header, halir_spectra *spectra, const halir_num *shared_x)
{
  SUBHDR subheader;
  size_t npts;

  if (subfile_offset >= 0) {
    if (fseek(fp, subfile_offset, SEEK_SET) != 0) {
      return 0;
    }
  }

  if (fread(&subheader, sizeof(subheader), 1, fp) != 1) {
    return 0;
  }

  npts = ((header->ftflgs & TXYXYS) != 0) ? (size_t)subheader.subnpts : (size_t)header->fnpts;
  if (npts == 0) {
    return 0;
  }

  spectra->ndatapnts = npts;
  spectra->wavenum = (halir_num*)calloc(npts, sizeof(halir_num));
  spectra->data = (halir_num*)calloc(npts, sizeof(halir_num));
  if ((spectra->wavenum == NULL) || (spectra->data == NULL)) {
    return 0;
  }

  if ((header->ftflgs & TXYXYS) != 0) {
    if ((header->ftflgs & TXVALS) != 0) {
      if (!spc_read_float_buffer(fp, npts, spectra->wavenum)) {
        return 0;
      }
    } else {
      spc_fill_linear_x(spectra, header->ffirst, header->flast);
    }
  } else if ((header->ftflgs & TXVALS) != 0) {
    memcpy(spectra->wavenum, shared_x, npts * sizeof(halir_num));
  } else {
    spc_fill_linear_x(spectra, header->ffirst, header->flast);
  }

  if (!spc_read_y_values(fp, npts, header->ftflgs, subheader.subexp, spectra->data)) {
    return 0;
  }

  return 1;
}

halir_result *
halir_result_read_spc(const char *file_path)
{
  FILE *fp;
  SPCHDR header;
  halir_result *result = NULL;
  size_t nspectra;
  int has_global_x;
  int has_xyxy_directory;
  halir_num *shared_x = NULL;
  SSFSTC *directory = NULL;

  if (file_path == NULL) {
    return NULL;
  }

  fp = fopen(file_path, "rb");
  if (fp == NULL) {
    return NULL;
  }

  if (fread(&header, sizeof(header), 1, fp) != 1) {
    fclose(fp);
    return NULL;
  }

  if (header.fversn != 0x4B) {
    fclose(fp);
    return NULL;
  }

  nspectra = ((header.ftflgs & TMULTI) != 0) ? (size_t)header.fnsub : 1;
  if (nspectra == 0) {
    fclose(fp);
    return NULL;
  }

  result = spc_alloc_result(nspectra);
  if (result == NULL) {
    fclose(fp);
    return NULL;
  }

  has_global_x = ((header.ftflgs & TXVALS) != 0) && ((header.ftflgs & TXYXYS) == 0);
  has_xyxy_directory = ((header.ftflgs & TXYXYS) != 0) && (header.fnpts != 0);
  if (has_global_x) {
    size_t shared_count = (size_t)header.fnpts;
    shared_x = (halir_num*)calloc(shared_count, sizeof(halir_num));
    if ((shared_x == NULL) || !spc_read_float_buffer(fp, shared_count, shared_x)) {
      free(shared_x);
      halir_result_free(result);
      fclose(fp);
      return NULL;
    }
  }

  if (has_xyxy_directory) {
    directory = (SSFSTC*)calloc(nspectra, sizeof(SSFSTC));
    if (directory == NULL) {
      free(shared_x);
      halir_result_free(result);
      fclose(fp);
      return NULL;
    }

    if (fseek(fp, (long)header.fnpts, SEEK_SET) != 0 ||
        fread(directory, sizeof(SSFSTC), nspectra, fp) != nspectra) {
      free(directory);
      free(shared_x);
      halir_result_free(result);
      fclose(fp);
      return NULL;
    }
  }

  for (size_t i = 0; i < nspectra; i++) {
    halir_spectra *spectra = &result->spectra[i];
    long subfile_offset = -1;

    if (directory != NULL) {
      subfile_offset = (long)directory[i].ssfposn;
    }

    if (!spc_read_subfile_at(fp, subfile_offset, &header, spectra, shared_x)) {
      free(directory);
      free(shared_x);
      halir_result_free(result);
      fclose(fp);
      return NULL;
    }
  }

  free(directory);
  free(shared_x);
  fclose(fp);
  return result;
}

halir_spectra *
halir_spectra_read_spc(const char *file_path)
{
  halir_result *result;
  halir_spectra *spectra;

  result = halir_result_read_spc(file_path);
  if ((result == NULL) || (result->nspectra == 0)) {
    halir_result_free(result);
    return NULL;
  }

  spectra = halir_spectra_create(result->spectra[0].ndatapnts);
  if (spectra == NULL) {
    halir_result_free(result);
    return NULL;
  }

  memcpy(spectra->wavenum, result->spectra[0].wavenum,
         result->spectra[0].ndatapnts * sizeof(halir_num));
  memcpy(spectra->data, result->spectra[0].data,
         result->spectra[0].ndatapnts * sizeof(halir_num));
  spectra->ndatapnts = result->spectra[0].ndatapnts;
  memcpy(&spectra->composition, &result->spectra[0].composition, sizeof(halir_compound));
  spectra->composition.hitran_head.molecs = NULL;
  spectra->composition.hitran_prms = NULL;
  spectra->composition.hitran_head.nisotp = 0;
  spectra->composition.hitran_head.ndatapnts = 0;

  halir_result_free(result);
  return spectra;
}
